### ISSUE TITLE
How to use in markdown..

### ISSUE THREAD

**Issue by asaji** [kura/pelican_vimeo#2]
Hi Kura,

Is there anyway to adapt this plugin to work in markdown documents?

**Comment by nullne** [comment]
@asaji   it seems that this plugin only supported on reStructuredText 
  i am also looking for markdown-supported video plugin and i decide to write my own

**Comment by colmoneill** [comment]
any update on this guys? @nullne did you publish your own plugin by any chance? Thanks!

**Comment by colmoneill** [comment]
what a silly bot @probot-stale[bot] this is not in any way resolved, there has been no interaction from the maker. If there is no desire to fix this, then that is one thing, but inactivity does not mean resolved
